### ISSUE TITLE
_isApprovedOrOwner and _exists are no longer included on open zeppelinERC721 contract

### ISSUE THREAD

**Issue by CaeraDenoir** [Cyfrin/foundry-nft-f23#14]
As the title says, _isApprovedOrOwner and _exists will not be defined when importing the open zeppelin ERC721 contract.

**Comment by PatrickAlphaC** [comment]
Thanks! You'll have to use the older version of openzeppelin... or remove those. What do you think is better/easier?

**Comment by CaeraDenoir** [comment]
Found a way using the functions on the newer version of openzeppelin. I think it's doing exactly the same checks as the old functions but i am not sure.
For the _isApprovedOrOwner, the newer _isAuthorized should do the trick. 
_isAuthorized(_ownerOf(tokenId), msg.sender, tokenId) should be equal to _isApprovedOrOwner(msg.sender, tokenId).

For the  _exists it is quite simple, the openzeppelin changelogs advise to just change it for _isAuthorized(_ownerOf(tokenId), msg.sender, tokenId).

Not sure about the  _isApprovedOrOwner one.

**Comment by cromewar** [comment]
Added this to chronological updates, thanks a lot @CaeraDenoir
