### ISSUE TITLE
error while deploying

### ISSUE THREAD

**Issue by lpetroulakis** [Cyfrin/foundry-nft-f23#16]
greetings devs!
while using the make deploy command for the basicNft.sol, while it compiles and the process is run till its end, the evm is set etc, i end up getting the following error.
```
Error: 
expected value at line 1 column 1
make: *** [deploy] Error 1
```
to add to that, when i try to manually verify it, it also fails. so i am left without an actual contract to go on to mint. i've tried a multitude of stuff, would appreciate any kind of assistance. Btw, i'm running it on mac, using zsh.

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464
