### ISSUE TITLE
error in make mint

### ISSUE THREAD

**Issue by rmayank-24** [Cyfrin/foundry-nft-f23#21]
make mint ARGS="--network sepolia"
[⠒] Compiling...
No files changed, compilation skipped
Traces:
  [1139609] → new DevOpsTools@0xC9C7eFbE4ACf80F7Eb542a85b22FE6fc0309187e
    └─ ← 5692 bytes of code

  [227375] → new MintNFT@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 1025 bytes of code

  [27943] MintNFT::run() 
    ├─ [3925] DevOpsTools::get_most_recent_deployment(NFT, 11155111 [1.115e7]) [delegatecall]
    │   ├─ [0] VM::readDir(./broadcast, 3) [staticcall]
    │   │   └─ ← "The path "./broadcast" is not allowed to be accessed for read operations."
    │   └─ ← "The path "./broadcast" is not allowed to be accessed for read operations."
    └─ ← "The path "./broadcast" is not allowed to be accessed for read operations."

Error: 
The path "./broadcast" is not allowed to be accessed for read operations.

**Comment by PatrickAlphaC** [comment]
Can you add this to your `foundry.toml`?

```
fs_permissions = [
    { access = "read", path = "./images/" },
    { access = "read", path = "./broadcast" },
]
```

**Comment by JR-Vickers** [comment]
> Can you add this to your `foundry.toml`?
> 
> ```
> fs_permissions = [
>     { access = "read", path = "./images/" },
>     { access = "read", path = "./broadcast" },
> ]
> ```

I'm not the OP but I had the same problem and this solution worked for me, thanks!
