### ISSUE TITLE
Metamask cannot display NFT images properly

### ISSUE THREAD

**Issue by segonse** [Cyfrin/foundry-nft-f23#23]
I first deployed BasicNFT to Sepolia and imported the contract address and TokenId into Metamask, but I couldn't get the picture, which I thought was a network problem. Then I deployed MoodNFT to anvil, but I couldn't get the smiley face either. Finally, I git cyfrin code locally and deploy MoodNFT to anvil with the same result

**Comment by segonse** [comment]
it's like this.

![image](https://github.com/Cyfrin/foundry-nft-f23/assets/129601241/7be606c9-d552-41f2-a292-f3f4b222bed5)

**Comment by NandanNNN** [comment]
I am also getting same issue

**Comment by Himchenhim** [comment]
I have the same issue too

**Comment by NandanNNN** [comment]
@PatrickAlphaC  can you please help here? i tried to look into other discussions also but didn't got much.

**Comment by PatrickAlphaC** [comment]
ah... whoops. Does the ipfs link work for you? 

This is one of the downsides of IPFS. Someone has to pin it! Looks like my pinning service was down. Can you try now?

**Comment by PatrickAlphaC** [comment]
(you'd have to delete and readd the NFT)

**Comment by luiscaceresd** [comment]
@PatrickAlphaC still not working, unfortunately. The weird part is that it displays fine on opensea -> https://testnets.opensea.io/assets/sepolia/0xc04ca966e0D160bfB9Ad4ACF01435552A17Fd342/2
https://sepolia.etherscan.io/nft/0xc04ca966e0d160bfb9ad4acf01435552a17fd342/2

![image](https://github.com/Cyfrin/foundry-nft-f23/assets/74666044/a3a2315f-9266-4205-813c-4502f1cc5e94)

**Comment by PatrickAlphaC** [comment]
what the... uh... Maybe the metamask API is buggin...

**Comment by luiscaceresd** [comment]
Yeah I kinda moved on :) my moody nfts is working fine tho!

**Comment by denisgulev** [comment]
Hello,
i run into the same problem of Metamask not showing the NFT image and wanted to share my solution.
After some research i found that Metamask has a toggle in the settings ("Display NFT media").
When turned on, i finally saw the two SVGs deployed with the MoodNft contract.

*NOTE:
![image](https://github.com/Cyfrin/foundry-nft-f23/assets/22997490/8701f55f-f04f-4b5b-8bd5-9154650c8234)

**Comment by segonse** [comment]
coooool!! Thanks denisgulev,This issue has been resolved!
