### ISSUE TITLE
Can't Mint the NFT

### ISSUE THREAD

**Issue by Onu-Daniel** [Cyfrin/foundry-nft-f23#24]
When I run the code  `make mint ARGS="--network sepolia"`  to mint the nft after deploying it, I get this error

` [6857] MintBasicNft::run()
    ├─ [3925] DevOpsTools::get_most_recent_deployment("BasicNft", 11155111 [1.115e7]) [delegatecall]
    │   ├─ [0] VM::readDir("./broadcast", 3) [staticcall]
    │   │   └─ ← the path broadcast is not allowed to be accessed for read operations
    │   └─ ← the path broadcast is not allowed to be accessed for read operations
    └─ ← the path broadcast is not allowed to be accessed for read operations

Error: 
script failed: the path broadcast is not allowed to be accessed for read operations
make: *** [Makefile:47: mint] Error 1`

**Comment by PatrickAlphaC** [comment]
Can you confirm your foundry.toml file matches what you see here on GitHub?

**Comment by Onu-Daniel** [comment]
It was a bit different. Thanks that solved it
