### ISSUE TITLE
IPFS image of the pug doesn't appear

### ISSUE THREAD

**Issue by prvasilew07** [Cyfrin/foundry-nft-f23#27]
The dog no longer appears in IPFS, it doesn't exist.

**Comment by haard18** [comment]
Try Reuploading the Image or just use a Gateway to navigate to the node you can get to a gateway using 
https://docs.ipfs.tech/concepts/ipfs-gateway/#gateway-providers

Also there is something Called IPFS garbage collector which deletes the files that are unpinned on your ipfs Node after a while. If that is the case reupload the Image
