### ISSUE TITLE
Failed to get EIP-1559 fees | Lesson 11 - Deploying 

### ISSUE THREAD

**Issue by dew10120** [Cyfrin/foundry-nft-f23#32]
HI, can some one help me with this please.

I'm trying to deploy the BasicNft to Sepolia test ne. However I get this error "Failed to get EIP-1559 fees"

I have included the Ethscan API key in the .env file also, 
any ideas why this occurs?

Thanks 
DEW

**Comment by dew10120** [comment]
> It could be an issue related to the RPC URL you're using. Could you try an alternative one?

I tried a different URL as well, cant seem to find a reason for this issue :(

**Comment by Equious** [comment]
You might need to share some code. Are your gas fees configured in your helperconfig? (max/priority fees?)

**Comment by pingmichael** [comment]
it happened to me,I tried " foundryup " on cmd and it was solved

**Comment by PtSik** [comment]
In the Makefile in you have to add -- legacy at the end of the deploy script
```
deploy:
	@forge script script/DeployBasicNft.s.sol:DeployBasicNft $(NETWORK_ARGS) --legacy
```

**Comment by Equious** [comment]
Resolving due to inactivity, please reopen if the problem persists.
