### ISSUE TITLE
I can't deploy and mint BasicNFT

### ISSUE THREAD

**Issue by jccimino1967** [Cyfrin/foundry-nft-f23#6]
Hello

When I deploy and mint BasicNft shows this error

for more security, i copy & paste the code from this github.

Copy BasicNft.sol and Interactions.s.sol (mintBasicNft )

can someone guide me

greetings

No files changed, compilation skipped
Traces:
  [639098] → new DevOpsTools@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    └─ ← 3192 bytes of code

  [249308] → new MintBasicNft@0x34A1D3fff3958843C43aD80F30b94c510645C316
    └─ ← 1024 bytes of code

  [49148] MintBasicNft::run() 
    ├─ [25130] DevOpsTools::e374cdf1(00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000007a69000000000000000000000000000000000000000000000000000000000000000842617369634e6674000000000000000000000000000000000000000000000000) [delegatecall]
    │   ├─ [0] VM::ffi([pwd]) 
    │   │   └─ ← "FFI disabled: run again with `--ffi` if you want to allow tests to call external scripts."
    │   └─ ← 0x0bc44503000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000594646492064697361626c65643a2072756e20616761696e207769746820602d2d6666696020696620796f752077616e7420746f20616c6c6f7720746573747320746f2063616c6c2065787465726e616c20736372697074732e00000000000000
    └─ ← "FFI disabled: run again with `--ffi` if you want to allow tests to call external scripts."

Gas used: 49148
Error: 
FFI disabled: run again with `--ffi` if you want to allow tests to call external scripts.

juancarlitos@JUANCA:~/solidity/foundry-nft-f23$ forge script script/Interactions.s.sol
[⠒] Compiling...
No files changed, compilation skipped
Traces:
  [639098] → new DevOpsTools@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    └─ ← 3192 bytes of code

  [249308] → new MintBasicNft@0x34A1D3fff3958843C43aD80F30b94c510645C316
    └─ ← 1024 bytes of code

  [49148] MintBasicNft::run() 
    ├─ [25130] DevOpsTools::e374cdf1(00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000007a69000000000000000000000000000000000000000000000000000000000000000842617369634e6674000000000000000000000000000000000000000000000000) [delegatecall]
    │   ├─ [0] VM::ffi([pwd]) 
    │   │   └─ ← "FFI disabled: run again with `--ffi` if you want to allow tests to call external scripts."
    │   └─ ← 0x0bc44503000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000594646492064697361626c65643a2072756e20616761696e207769746820602d2d6666696020696620796f752077616e7420746f20616c6c6f7720746573747320746f2063616c6c2065787465726e616c20736372697074732e00000000000000
    └─ ← "FFI disabled: run again with `--ffi` if you want to allow tests to call external scripts."

Gas used: 49148
Error: 
FFI disabled: run again with `--ffi` if you want to allow tests to call external scripts.

**Comment by jccimino1967** [comment]
i get the same error typing

 forge script script/Interactions.s.sol:MintBasicNft --rpc-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY_SEPOLIA --broadcast -vvvv

**Comment by jccimino1967** [comment]
my .ENV 

SEPOLIA_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/0X9NUgDwS8wsjrLNmhUWGfodaCR_9iGB
PRIVATE_KEY_SEPOLIA=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ETHERSCAN_API_KEY=QX8FPTXRMQF3XGSCVJGKJAYUI6925B344Z

**Comment by AlexGorgut** [comment]
Did you put your ``` ffi = true ``` in the foundry.toml file? I am not sure that it could help.

**Comment by jccimino1967** [comment]
Hello Alex

Yes. Right now I'm studying a bit of bash to understand what the file get_recent_deployment.sh
that shows me the console output does. 

Thank you so much





 forge script script/Interactions.s.sol:MintBasicNft --ffi  --rpc-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY_SEPOLIA --broadcast
 -vvvv 
[⠔] Compiling...
No files changed, compilation skipped
2023-08-28T09:54:07.905499Z ERROR apply:ext: evm::cheatcodes: non-empty stderr args=["bash", "/home/juancarlitos/solidity/foundry-nft-f23/lib/foundry-devops/src/get_recent_deployment.sh", "BasicNft", "11155111", "/home/juancarlitos/solidity/foundry-nft-f23//broadcast"] stderr="/home/juancarlitos/solidity/foundry-nft-f23/lib/foundry-devops/src/get_recent_deployment.sh: line 13: syntax error near unexpected token `<'\n/home/juancarlitos/solidity/foundry-nft-f23/lib/foundry-devops/src/get_recent_deployment.sh: line 13: `echo <contractName> <chainId>'\n"
Traces:
  [639098] → new DevOpsTools@0x28B4Ae26A4FEfb204Cac0743152AC99a2Fdb5260
    └─ ← 3192 bytes of code

  [249914] → new MintBasicNft@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 1027 bytes of code

  [63474] MintBasicNft::run() 
    ├─ [35704] DevOpsTools::e374cdf1(00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000aa36a7000000000000000000000000000000000000000000000000000000000000000842617369634e6674000000000000000000000000000000000000000000000000) [delegatecall]
    │   ├─ [0] VM::ffi([pwd]) 
    │   │   └─ ← 0x2f686f6d652f6a75616e6361726c69746f732f736f6c69646974792f666f756e6472792d6e66742d663233
    │   ├─ [0] VM::toString(11155111 [1.115e7]) [staticcall]
    │   │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000083131313535313131000000000000000000000000000000000000000000000000
    │   ├─ [0] VM::ffi([bash, /home/juancarlitos/solidity/foundry-nft-f23/lib/foundry-devops/src/get_recent_deployment.sh, BasicNft, 11155111, /home/juancarlitos/solidity/foundry-nft-f23//broadcast]) 
    │   │   └─ ← 0x4a55414e4341524c49544f53
    │   ├─ [0] console::log(Return Data:) [staticcall]
    │   │   └─ ← ()
    │   ├─ [0] console::log(0x4a55414e4341524c49544f53) [staticcall]
    │   │   └─ ← ()
    │   └─ ← 0x0000000000000000000000004a55414e4341524c49544f530000000000000000
    ├─ [0] VM::startBroadcast() 
    │   └─ ← ()
    └─ ← "EvmError: Revert"



== Logs ==
  Return Data:
  0x4a55414e4341524c49544f53
Error: 
Script failed.

**Comment by jccimino1967** [comment]
SOLVED!!

Follow this discussion 

https://github.com/Cyfrin/foundry-full-course-f23/discussions/437
